- docs/rules.md
- example/BUILD.bazel
- example/example_lock.bzl
- pycross/BUILD.bazel
- pycross/defs.bzl
- pycross/private/BUILD.bazel
- pycross/private/lock_file.bzl
- pycross/private/pypi_file.bzl
- pycross/private/tools/bzl_lock_generator.py
Before we were guessing the URL at pythonhosted.org based on
https://github.com/pypa/warehouse/issues/1944. This works in theory, but
there are over 100k wheels uploaded with the wrong python tags (i.e.,
the tag in index metadata doesn't match the tag in the .whl filename).
Instead, pypi_file takes a package name, version, filename, and sha256,
fetches package metadata from pypi (or a compatible index), and uses
that URL to download the package. It's still pure Bazel, thanks to the
PyPI JSON API and Bazel's JSON support.
> Adds a pypi_file repo rule.

- docs/rules.md
- example/BUILD.bazel
- example/example_lock.bzl
- example/poetry.lock
- example/pyproject.toml
- pycross/private/lock_file.bzl
- pycross/private/tools/bzl_lock_generator.py
- pycross/private/tools/lock_model.py
- pycross/private/tools/poetry_translator.py
- Changed the package "key" format from `name-version` to `name@version`. The `@` character is not permitted in package names (unlike the hyphen), which allows unambiguously supporting just the package name in various attributes which is then resolved to a package + version. (Previously, for example, `package-0` could have either been `package` version 0, or a versionless package named `package-0`.)
- Add support for specifying additional build dependencies with `package_build_dependencies`.
> Change package name format and add support for package build dependencies

- example/BUILD.bazel
- example/example_lock.bzl
- pycross/private/tools/bzl_lock_generator.py
- pycross/private/tools/lock_model.py
Adds an optional urls list to PackageFile and removes the UrlFile
wrapper. If a PackageFile has urls - whether wheel or sdist - http_file
will be used to fetch it rather than pypi_file.
> Refactor files that have provided URLs

- pycross/private/pypi_file.bzl
https://discuss.python.org/t/backwards-incompatible-change-to-pypi-json-api/17154
> Fix after backwards-incompatible pypi change

- pycross/private/tools/wheel_builder.py
- pycross/private/wheel_build.bzl
- pycross/private/wheel_library.bzl
Previously we were including transitive packages (`PyInfo.imports`) in the list of build dependencies, but they weren't being added to the Bazel sandbox.
Also, if debug mode is enabled (`RULES_PYCROSS_DEBUG=1`), we run `python -m site` prior to the build to show the site configuration.
> Correctly add transitive deps when building a wheel

- examples/pdm/.bazelrc
- pycross/private/wheel_build.bzl
With `--experimental_sibling_repository_layout` enabled, our assumptions about build dependency import paths were broken.
> Make pycross_wheel_build compatible with --experimental_sibling_repository_layout

- pycross/private/cc_toolchain_util.bzl
- pycross/private/wheel_build.bzl
The `CFLAGS` env variable does not seem to be honored.
Regardless, passing the options through command line flags is better because on build failure the printed clang invocation would have these options and hence it's easier to debug.
> Bring back copts and linkopts

- pycross/private/tools/BUILD.bazel
This dependency is required for this to work with Python 3.11.
> [Easy] Fixed wheel builder bug.

- pycross/private/tools/pdm_translator.py
fixes 
`__main__.MismatchedVersionException: Found no packages to satisfy dependency (name=sphinx-basic-ng, spec=)`
which occurs if a package does not specify any constraints for a dependency.
> fix: pdm translator fails to resolve dependency if pre-release version is required

- pycross/private/tools/BUILD.bazel
- pycross/private/tools/crossenv/BUILD.bazel
This fixes breakage for users of this repository when --experimental_python_import_all_repositories=false is set, which the Bazel team would like to do in https://github.com/bazelbuild/bazel/issues/2636.
See also https://github.com/bazelbuild/rules_python/issues/792
Without this change, users get the error:.
```
runfiles/rules_pycross/pycross/private/tools/wheel_installer.py", line 14, in <module>
from pycross.private.tools import namespace_pkgs
ModuleNotFoundError: No module named 'pycross'
```
> fix: Add imports to allow experimental_python_import_all_repositories

- pycross/private/tools/wheel_installer.py
I  experienced this error https://github.com/openai/tiktoken/pull/152 and figured it is better to remove all __pycache__ directories in general
> fix: Don't generate pyc files on installation

- .github/workflows/ci.yaml
- e2e/bzlmod/MODULE.bazel
- e2e/bzlmod/lock_file/pdm_lock.bzl
- e2e/bzlmod/lock_file/poetry_lock.bzl
- e2e/workspace/WORKSPACE
- e2e/workspace/pdm/lock.bzl
- e2e/workspace/poetry/lock.bzl
Our Github darwin runners seemed to switch to arm64. This required downgrading two 3.10.11 since 3.10.12 doesn't seem available for Github + darwin, and changing the arch.
> Fix e2e tests

- MODULE.bazel
- pycross/private/bzlmod/BUILD.bazel
- pycross/private/bzlmod/lock_import.bzl
- pycross/private/bzlmod/lock_repos.bzl
`MODULE.bazel.lock` also contains all the repos created by `lock_import` and `lock_repos`.
This makes the file extremely big (>1MB in our monorepo).
Since bazel `7.1.1` [`extension_metadata`](https://bazel.build/rules/lib/builtins/module_ctx#extension_metadata) allows marking an extension as being reproducible.
Some more background:
- https://github.com/bazelbuild/bazel/issues/20272
- https://github.com/aspect-build/rules_js/pull/1541
- https://github.com/bazelbuild/rules_python/pull/1892
- https://bazel.build/rules/lib/builtins/module_ctx#extension_metadata
> feat(bzlmod): mark lock_import and lock_repos as reproducible

- pycross/private/repo_venv_utils.bzl
`result.return_code` is an int
Also interpolate stderr from the subprocess
> fix: int() is not callable, better error message

- README.md
Updates README.md with instructions on how to use Gazelle plugin from `rules_python`.
Closes https://github.com/jvolkman/rules_pycross/issues/100
> Update README with a Gazelle how-to

- CHANGELOG.md
- pycross/private/toolchain_helpers.bzl
`rules_python` 1.0.0 [removes](https://github.com/bazelbuild/rules_python/blob/6a04d3832e82fec0a7b0675e9964b360bc358554/CHANGELOG.md?plain=1#L211) the `DEFAULT_PYTHON_VERSION` constant from the Python hub repo's `interpreters.bzl` file. Instead, the version must be read from the `versions.bzl` file, introduced in `rules_python` 0.37.0.
As a result, creating a Python environment with `rules_pycross` (main branch) and `rules_python` 1.0.0 leads to the following error.
```text
INFO: Repository rules_pycross++environments+pycross_environments_myproject instantiated at:
<builtin>: in <toplevel>
Repository rule pycross_environments_repo defined at:
/private/var/tmp/_bazel_gabriel/17eb730aec70ae18dde0e6ba1d906dff/external/rules_pycross+/pycross/private/toolchain_helpers.bzl:430:44: in <toplevel> …
```
> fix: Obtain default Python version for Python hub repo from versions.bzl file

- CHANGELOG.md
- e2e/pdm/always_build/MODULE.bazel
- e2e/pdm/build_wheel/MODULE.bazel
- e2e/pdm/local_wheel/MODULE.bazel
- e2e/pdm/requirements/MODULE.bazel
- e2e/poetry/always_build/MODULE.bazel
- e2e/poetry/build_wheel/MODULE.bazel
- e2e/poetry/local_wheel/MODULE.bazel
- e2e/poetry/requirements/MODULE.bazel
- e2e/uv/always_build/MODULE.bazel
- e2e/uv/build_wheel/MODULE.bazel
- e2e/uv/local_wheel/MODULE.bazel
- e2e/uv/requirements/MODULE.bazel
- pycross/private/tools/lock_model.py
- pycross/private/tools/pdm_translator.py
- pycross/private/tools/poetry_translator.py
- pycross/private/tools/raw_lock_resolver.py
- pycross/private/tools/uv_translator.py
- pycross/tests/uv/lock_0_2_35/expected.json
- pycross/tests/uv/lock_0_4_0_virtual/expected.json
- pycross/tests/uv/lock_0_4_27_legacy_dev_dependencies/expected.json
- pycross/tests/uv/lock_0_4_27_pep735/expected.json
- pycross/tests/uv/lock_pre_0_2_35/expected.json
With this change, pycross will use an imported lock file's `requires-python` (or equivalent) specifier set to further filter the list of target Python environments. For example, if Python 3.8 is in the full list of target environments, but the imported lock file specifies '>=3.9', Python 3.8 environments will be filtered out.
> feat: only consider Python versions that match a lock file's requires-python set

- pycross/private/toolchain_helpers.bzl
As seen here:
https://github.com/bazelbuild/rules_python/blob/b5729b41ef18393c2609aa1633607695175a7419/python/versions.bzl#L625-L696
some of the python platforms now end with `-freethreaded`. This makes my project [error](https://github.com/jvolkman/rules_pycross/blob/20fba49f17655c45f51e1bc293a329c8e1785abf/pycross/private/toolchain_helpers.bzl#L62) with:
```
Error in fail: Unknown platform: aarch64-apple-darwin-freethreaded
```
With the changes in this PR, the error goes away.
I'm not yet confident in my bazel and pycross skills to know if this is the best solution to the problem.
> Fix for: "Error in fail: Unknown platform: aarch64-apple-darwin-freethreaded"

- pycross/private/package_repo.bzl
Some packages don't have sdist wheels. There are other places that check for this
(https://github.com/jvolkman/rules_pycross/blob/3e9e105d9d8a0853469be3c87067730322ceb34b/pycross/private/package_repo.bzl#L63) but it was missing here.
> fix: Check for existence of sdist wheel

- pycross/private/tools/raw_lock_resolver.py
Unfortunately `str.join` won't stringify elements in its argument, even when they have a `__str__`; we have to do it ourselves. Otherwise an exception is raised:
```
Traceback (most recent call last):
File "/private/var/tmp/_bazel_peter/dfecb8ec3f6f433d8509be7ebe017232/external/rules_pycross~/pycross/private/tools/raw_lock_resolver.py", line 579, in <module>
main(parse_flags())
File "/private/var/tmp/_bazel_peter/dfecb8ec3f6f433d8509be7ebe017232/external/rules_pycross~/pycross/private/tools/raw_lock_resolver.py", line 569, in main
result = resolve(args)
^^^^^^^^^^^^^
File "/private/var/tmp/_bazel_peter/dfecb8ec3f6f433d8509be7ebe017232/external/rules_pycross~/pycross/private/tools/raw_lock_resolver.py", line 455, in resolve
f"{', '.join(builds)}"
^^^^^^^^^^^^^^^^^
TypeError: sequence item …
```
> fix: stringify keys when reporting sdist-only packages

- pycross/private/tools/wheel_builder.py
Seems like aarch64 linux python 3.12 doesn't set this correctly with the latest setuptools so you end up hitting the issue linked in the comment
> Set LDCXXSHARED

- pycross/private/bzlmod/lock_file.bzl
- pycross/private/lock_file_repo.bzl
It seems like without these changing the generated bzl lockfile can
result in not reruning these rules and getting failures like:
```
ERROR: no such package '@@[unknown repo 'pycross_lock_file_wheel_mypy_1.16.1_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64' requested from @@rules_pycross++lock_file+modular_pip_lock_file_repo (did you mean 'pycross_lock_file_wheel_mypy_1.13.0_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64'?)]//file': The repository '@@[unknown repo 'pycross_lock_file_wheel_mypy_1.16.1_cp312_cp312_manylinux_2_17_x86_64.manylinux2014_x86_64.manylinux_2_28_x86_64' requested from @@rules_pycross++lock_file+modular_pip_lock_file_repo (did you mean 'pycross_lock_file_wheel_mypy_1.13.0_cp312_cp312_manylinux_2_17_x86_64.m …
```
> Add more module_ctx.watch calls

- pycross/private/bzlmod/BUILD.bazel
- pycross/private/bzlmod/environments.bzl
- pycross/private/bzlmod/lock_file.bzl
- pycross/private/bzlmod/pycross.bzl
- pycross/private/bzlmod/toolchains.bzl
As far as I can tell these should be reproducible so this removes tons
from the MODULE.bazel.lock, in our case ~12k lines / 800k
> Mark more extensions as reproducible

- pycross/private/tools/BUILD.bazel
- pycross/toolchain.bzl
* Adds missing py_test import to tools build file, as well as importing PyRuntimeInfo from rules_python explicitly since Python providers were removed from Bazel in 8.0.
> Add missing Imports

- pycross/private/tools/wheel_installer.py
This makes it easier to post process these scripts to make them actually
work with the correct interpreter, which is useful when copying them to
venvs. This new value follows pep-491
before:
```
#!/bin/sh
'''exec' '/usr/bin/env python3' "$0" "$@"
' '''
import re
import sys
from httpx import main
if __name__ == "__main__":
sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
sys.exit(main())
```
after:
```
#!python
import re
import sys
from httpx import main
if __name__ == "__main__":
sys.argv[0] = re.sub(r"(-script\.pyw|\.exe)?$", "", sys.argv[0])
sys.exit(main())
```
> Improve bin scripts shebangs
